### ISSUE TITLE
Show note on hover

### ISSUE THREAD

**Issue by GBratsos** [dvnc/annotator#2]
Hello,

I just saw this awesome work! But i think it would be a nice idea to show the not on hover after you have created one.

What do you think?

**Comment by bharani91** [comment]
Thanks for the suggestion. I had thought of showing the note on hover but later decided that since it is not something that everyone would need, it doesn't make sense to build it into the plugin itself.

This is fairly easy to do though - You'll just need to attach a listener for mouseover/mouseout on the `.annotation` element. Inside that event listener, you can get the id of the annotation by using the `data-id` attribute of the annotation. You can use this to find the annotation object.

``` javascript
var annotationID = $(e.target).data("id");
var annotation = annotator.findAnnotation(annotationID);
// console.log(annotation.note, annotation.tags);
```
